//! # DTU — Dependency Test Unit Framework
//!
//! DTUs are stateful in-memory clones of external APIs. During scenario
//! validation, the Scenario Validator talks to DTU clones instead of real
//! services. Each clone maintains realistic state transitions.
//!
//! ## Architecture
//!
//! ```text
//! DtuProvider trait ─── Stripe clone
//!                  ├── Auth0 clone
//!                  ├── SendGrid clone  (Phase 5)
//!                  ├── Supabase clone  (Phase 5)
//!                  └── Twilio clone    (Phase 5)
//! ```
//!
//! The `DtuRegistry` manages all registered providers and routes
//! requests to the correct clone based on the provider ID.

pub mod stripe;
pub mod auth0;
pub mod sendgrid;
pub mod supabase;
pub mod twilio;

use std::collections::HashMap;
use std::sync::Arc;

use planner_schemas::{DtuRequest, DtuResponse, DtuProviderInfo, DtuConfigV1};

// ---------------------------------------------------------------------------
// DtuProvider trait
// ---------------------------------------------------------------------------

/// Trait implemented by each DTU behavioral clone.
/// All clones are stateful — they maintain in-memory state that
/// persists across requests within a single scenario validation run.
pub trait DtuProvider: Send + Sync {
    /// Provider metadata (ID, name, supported endpoints, etc.).
    fn info(&self) -> &DtuProviderInfo;

    /// Handle an API request and return a response.
    /// The clone should update its internal state as appropriate.
    fn handle_request(&self, request: &DtuRequest) -> DtuResponse;

    /// Reset all internal state (called between scenario runs).
    fn reset(&self);

    /// Apply a DTU configuration generated by Ralph.
    /// Seeds initial state, configures behavioral rules and failure modes.
    fn apply_config(&self, config: &DtuConfigV1);

    /// Inject a failure mode for edge-case testing.
    fn inject_failure(&self, endpoint: &str, status_code: u16, error_body: serde_json::Value);

    /// Clear all injected failure modes.
    fn clear_failures(&self);

    /// Get current state snapshot (for debugging / test assertions).
    fn state_snapshot(&self) -> serde_json::Value;
}

// ---------------------------------------------------------------------------
// DtuRegistry
// ---------------------------------------------------------------------------

/// Registry of all available DTU providers.
/// Routes requests to the correct clone based on provider ID.
pub struct DtuRegistry {
    providers: HashMap<String, Arc<dyn DtuProvider>>,
}

impl DtuRegistry {
    /// Create a new empty registry.
    pub fn new() -> Self {
        DtuRegistry {
            providers: HashMap::new(),
        }
    }

    /// Create a registry pre-loaded with all Phase 4 providers.
    pub fn with_phase4_defaults() -> Self {
        let mut registry = Self::new();
        registry.register(Arc::new(stripe::StripeDtu::new()));
        registry.register(Arc::new(auth0::Auth0Dtu::new()));
        registry
    }

    /// Create a registry pre-loaded with all Phase 5 providers (all 5 APIs).
    pub fn with_phase5_defaults() -> Self {
        let mut registry = Self::with_phase4_defaults();
        registry.register(Arc::new(sendgrid::SendGridDtu::new()));
        registry.register(Arc::new(supabase::SupabaseDtu::new()));
        registry.register(Arc::new(twilio::TwilioDtu::new()));
        registry
    }

    /// Register a DTU provider.
    pub fn register(&mut self, provider: Arc<dyn DtuProvider>) {
        let id = provider.info().id.clone();
        self.providers.insert(id, provider);
    }

    /// Look up a provider by ID.
    pub fn get(&self, provider_id: &str) -> Option<&Arc<dyn DtuProvider>> {
        self.providers.get(provider_id)
    }

    /// Route a request to the correct provider.
    pub fn route_request(
        &self,
        provider_id: &str,
        request: &DtuRequest,
    ) -> Result<DtuResponse, DtuError> {
        let provider = self.providers.get(provider_id)
            .ok_or_else(|| DtuError::ProviderNotFound(provider_id.to_string()))?;
        Ok(provider.handle_request(request))
    }

    /// Reset all providers (between scenario runs).
    pub fn reset_all(&self) {
        for provider in self.providers.values() {
            provider.reset();
        }
    }

    /// Apply Ralph-generated configs to the appropriate providers.
    pub fn apply_configs(&self, configs: &[DtuConfigV1]) {
        for config in configs {
            if let Some(provider) = self.providers.get(&config.provider_id) {
                provider.apply_config(config);
            }
        }
    }

    /// List all registered providers.
    pub fn list_providers(&self) -> Vec<&DtuProviderInfo> {
        self.providers.values().map(|p| p.info()).collect()
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// DTU framework errors.
#[derive(Debug, thiserror::Error)]
pub enum DtuError {
    #[error("DTU provider not found: {0}")]
    ProviderNotFound(String),

    #[error("DTU request failed: {0}")]
    RequestFailed(String),

    #[error("DTU state error: {0}")]
    StateError(String),
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_phase4_defaults_has_stripe_and_auth0() {
        let registry = DtuRegistry::with_phase4_defaults();
        assert!(registry.get("stripe").is_some());
        assert!(registry.get("auth0").is_some());
        assert!(registry.get("sendgrid").is_none()); // Phase 5 only
    }

    #[test]
    fn registry_route_unknown_provider_returns_error() {
        let registry = DtuRegistry::new();
        let request = DtuRequest {
            method: "GET".into(),
            path: "/v1/test".into(),
            query_params: vec![],
            headers: vec![],
            body: None,
        };
        let result = registry.route_request("nonexistent", &request);
        assert!(result.is_err());
    }

    #[test]
    fn registry_list_providers() {
        let registry = DtuRegistry::with_phase4_defaults();
        let providers = registry.list_providers();
        assert_eq!(providers.len(), 2);
        let ids: Vec<&str> = providers.iter().map(|p| p.id.as_str()).collect();
        assert!(ids.contains(&"stripe"));
        assert!(ids.contains(&"auth0"));
    }

    #[test]
    fn registry_phase5_defaults_has_all_five() {
        let registry = DtuRegistry::with_phase5_defaults();
        let providers = registry.list_providers();
        assert_eq!(providers.len(), 5);
        assert!(registry.get("stripe").is_some());
        assert!(registry.get("auth0").is_some());
        assert!(registry.get("sendgrid").is_some());
        assert!(registry.get("supabase").is_some());
        assert!(registry.get("twilio").is_some());
    }
}
