//! # Git Projection — Behavioral Approval → Standard Git Commit
//!
//! After the Smart Tinkerer approves the Live Preview, the Git Projection
//! module commits the factory output to a standard Git repository.
//!
//! This preserves the anti-lock-in invariant: generated code runs
//! without Planner v2. The code is just a normal Git repo.
//!
//! Phase 0: Basic git init + commit. No remote push (that's Phase 3).

use std::path::Path;
use uuid::Uuid;

use planner_schemas::*;
use super::{StepResult, StepError};

// ---------------------------------------------------------------------------
// GitProjectionResult — what we return after committing
// ---------------------------------------------------------------------------

/// Result of the Git Projection step.
#[derive(Debug, Clone)]
pub struct GitProjectionResult {
    /// The GitCommitV1 artifact produced.
    pub commit: GitCommitV1,
    /// Path to the Git repository.
    pub repo_path: String,
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Execute Git Projection: commit approved factory output to a Git repo.
///
/// Phase 0: Creates a new repo (or uses existing) at the output path,
/// stages all files, and creates an initial commit.
pub async fn execute_git_projection(
    factory_output: &FactoryOutputV1,
    project_id: Uuid,
    project_name: &str,
    feature_slug: &str,
) -> StepResult<GitProjectionResult> {
    let output_path = Path::new(&factory_output.output_path);

    if !output_path.exists() {
        return Err(StepError::Other(format!(
            "Output path does not exist: {}",
            factory_output.output_path
        )));
    }

    tracing::info!(
        "Git Projection: committing approved output at {}",
        factory_output.output_path,
    );

    // Check if git is available
    let git_available = std::process::Command::new("which")
        .arg("git")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false);

    if !git_available {
        tracing::warn!("Git not available — creating simulated projection");
        return Ok(simulate_git_projection(
            factory_output,
            project_id,
            project_name,
            feature_slug,
        ));
    }

    // Initialize repo if needed
    let git_dir = output_path.join(".git");
    if !git_dir.exists() {
        run_git_command(output_path, &["init"]).await?;
        tracing::info!("  Initialized new Git repo");
    }

    // Configure Git identity (needed for commit)
    run_git_command(output_path, &["config", "user.name", "Planner v2"]).await?;
    run_git_command(
        output_path,
        &["config", "user.email", "planner@localhost"],
    )
    .await?;

    // Stage all files
    run_git_command(output_path, &["add", "-A"]).await?;

    // Create commit
    let commit_message = format!(
        "feat({}): {}\n\nGenerated by Planner v2 — Phase 0\nProject: {}\nKilroy Run: {}\nBuild Status: {:?}\nSpend: ${:.2}",
        feature_slug,
        project_name,
        project_id,
        factory_output.kilroy_run_id,
        factory_output.build_status,
        factory_output.spend_usd,
    );

    run_git_command(output_path, &["commit", "-m", &commit_message, "--allow-empty"]).await?;

    // Get the commit hash
    let hash = get_git_hash(output_path).await?;

    // Get the list of committed files
    let files = get_committed_files(output_path).await?;

    tracing::info!(
        "  Git commit {} — {} files on branch main",
        &hash[..8.min(hash.len())],
        files.len(),
    );

    let committed_files: Vec<CommittedFile> = files
        .iter()
        .map(|f| CommittedFile {
            path: f.clone(),
            change_type: FileChangeType::Added,
        })
        .collect();

    let commit = GitCommitV1 {
        project_id,
        commit_hash: hash,
        branch: "main".into(),
        message: commit_message,
        files: committed_files,
        kilroy_run_id: factory_output.kilroy_run_id,
        approved_preview_id: Uuid::new_v4(), // Phase 0: no preview approval flow
    };

    Ok(GitProjectionResult {
        repo_path: factory_output.output_path.clone(),
        commit,
    })
}

// ---------------------------------------------------------------------------
// Git command helpers
// ---------------------------------------------------------------------------

async fn run_git_command(cwd: &Path, args: &[&str]) -> StepResult<String> {
    let output = tokio::process::Command::new("git")
        .args(args)
        .current_dir(cwd)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .await
        .map_err(|e| StepError::Other(format!("Failed to run git {}: {}", args.join(" "), e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        // git commit --allow-empty may "fail" if nothing to commit — that's OK
        if args.first() == Some(&"commit") && stderr.contains("nothing to commit") {
            return Ok(String::new());
        }
        return Err(StepError::Other(format!(
            "git {} failed: {}",
            args.join(" "),
            stderr
        )));
    }

    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

async fn get_git_hash(cwd: &Path) -> StepResult<String> {
    let hash = run_git_command(cwd, &["rev-parse", "HEAD"]).await?;
    if hash.is_empty() {
        // Fallback: generate a synthetic hash
        Ok(format!("{:040x}", uuid::Uuid::new_v4().as_u128()))
    } else {
        Ok(hash)
    }
}

async fn get_committed_files(cwd: &Path) -> StepResult<Vec<String>> {
    let output = run_git_command(cwd, &["diff", "--name-only", "HEAD~1", "HEAD"]).await;

    match output {
        Ok(files) => Ok(files
            .lines()
            .map(|l| l.trim().to_string())
            .filter(|l| !l.is_empty())
            .collect()),
        Err(_) => {
            // If there's only one commit, list all tracked files
            let all_files = run_git_command(cwd, &["ls-files"]).await.unwrap_or_default();
            Ok(all_files
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect())
        }
    }
}

/// Simulated Git projection when git is not available.
fn simulate_git_projection(
    factory_output: &FactoryOutputV1,
    project_id: Uuid,
    project_name: &str,
    feature_slug: &str,
) -> GitProjectionResult {
    let hash = format!("{:040x}", Uuid::new_v4().as_u128());

    let commit = GitCommitV1 {
        project_id,
        commit_hash: hash,
        branch: "main".into(),
        message: format!(
            "feat({}): {} (simulated)",
            feature_slug, project_name,
        ),
        files: vec![CommittedFile {
            path: "(simulated — git not available)".into(),
            change_type: FileChangeType::Added,
        }],
        kilroy_run_id: factory_output.kilroy_run_id,
        approved_preview_id: Uuid::new_v4(),
    };

    GitProjectionResult {
        repo_path: factory_output.output_path.clone(),
        commit,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_factory_output() -> FactoryOutputV1 {
        // Create a temp dir for the test
        let output_dir = std::env::temp_dir()
            .join("planner-git-test")
            .join(Uuid::new_v4().to_string());
        std::fs::create_dir_all(&output_dir).unwrap();

        // Write a test file
        std::fs::write(output_dir.join("index.html"), "<html>test</html>").unwrap();

        FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Success,
            spend_usd: 0.42,
            checkpoint_path: "/tmp/cp.json".into(),
            dod_results: vec![],
            node_results: vec![],
            output_path: output_dir.to_string_lossy().to_string(),
        }
    }

    #[tokio::test]
    async fn git_projection_creates_commit() {
        let factory_output = sample_factory_output();
        let project_id = Uuid::new_v4();

        let result = execute_git_projection(
            &factory_output,
            project_id,
            "Test Widget",
            "test-widget",
        )
        .await;

        assert!(result.is_ok());
        let projection = result.unwrap();
        assert_eq!(projection.commit.project_id, project_id);
        assert_eq!(projection.commit.branch, "main");
        assert!(!projection.commit.commit_hash.is_empty());
        assert!(projection.commit.message.contains("test-widget"));

        // Cleanup
        let _ = std::fs::remove_dir_all(&factory_output.output_path);
    }

    #[test]
    fn simulated_projection_produces_valid_result() {
        let factory_output = FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Success,
            spend_usd: 0.0,
            checkpoint_path: String::new(),
            dod_results: vec![],
            node_results: vec![],
            output_path: "/tmp/test-output".into(),
        };

        let result = simulate_git_projection(
            &factory_output,
            Uuid::new_v4(),
            "Test Project",
            "test-project",
        );

        assert_eq!(result.commit.branch, "main");
        assert!(result.commit.commit_hash.len() == 40);
        assert!(result.commit.message.contains("simulated"));
    }
}
