//! # Telemetry Presenter — Factory Output → Plain English
//!
//! The Telemetry Presenter has three responsibilities:
//!
//! 1. **Factory Question Classification**: Classify escalations as
//!    intent gaps (→ Consequence Card) or implementation details
//!    (→ autonomous resolution).
//!
//! 2. **Satisfaction Score Translation**: Convert tiered pass rates
//!    into plain-English messages the Smart Tinkerer can understand.
//!    The user NEVER sees numeric scores.
//!
//! 3. **Consequence Cards**: Generate cards for Critical gate failures,
//!    High gate failures, budget warnings, and budget exhaustion.
//!
//! 4. **Live Preview**: (Phase 2+) Serve factory output in Docker sandbox.
//!    Phase 1: Just report the output path.
//!
//! Model: claude-haiku-4-5 (fast, cheap plain-English translation)

use uuid::Uuid;

use crate::llm::{CompletionRequest, DefaultModels, Message, Role};
use crate::llm::providers::LlmRouter;
use planner_schemas::*;
use super::{StepResult, StepError};

// ---------------------------------------------------------------------------
// Telemetry Report — the output of the Telemetry Presenter
// ---------------------------------------------------------------------------

/// Plain-English telemetry report for the Smart Tinkerer.
#[derive(Debug, Clone)]
pub struct TelemetryReport {
    /// The headline message for the user.
    pub headline: String,

    /// Detailed plain-English summary of what happened.
    pub summary: String,

    /// Path where the built app lives (for Live Preview in Phase 1+).
    pub preview_path: Option<String>,

    /// Whether the user needs to take action.
    pub needs_user_action: bool,

    /// Consequence cards generated by this round (if any).
    pub consequence_cards: Vec<ConsequenceCardV1>,

    /// Satisfaction message from the validator.
    pub satisfaction_message: String,
}

// ---------------------------------------------------------------------------
// System prompt for Haiku-driven translation
// ---------------------------------------------------------------------------

const TELEMETRY_SYSTEM_PROMPT: &str = r#"You are the Telemetry Presenter for Planner v2. Your job: translate factory execution results into plain English for a non-technical user (the "Smart Tinkerer").

## Rules
1. NEVER show numeric scores, percentages, or technical metrics to the user
2. Use warm, clear language — like explaining results to a smart friend
3. Focus on WHAT HAPPENED and WHAT IT MEANS, not technical details
4. If something failed, explain what didn't work in terms the user understands
5. If the user needs to act, be specific about what you need from them
6. Keep it under 200 words

## Output Format
Respond with ONLY a JSON object (no markdown fences):

{
  "headline": "One-sentence summary (like an email subject line)",
  "summary": "2-4 sentence plain-English explanation of what happened and what comes next",
  "needs_user_action": true|false,
  "action_description": "What the user should do (null if needs_user_action is false)"
}"#;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a telemetry report from factory output and validation results.
///
/// Phase 0: Uses Haiku for translation. No Docker sandbox (just output path).
pub async fn execute_telemetry_presentation(
    router: &LlmRouter,
    factory_output: &FactoryOutputV1,
    satisfaction: &SatisfactionResultV1,
    budget: &RunBudgetV1,
    project_id: Uuid,
) -> StepResult<TelemetryReport> {
    tracing::info!("Telemetry Presenter: translating results to plain English");

    // Build the context for Haiku
    let context = build_telemetry_context(factory_output, satisfaction, budget);

    let request = CompletionRequest {
        system: Some(TELEMETRY_SYSTEM_PROMPT.to_string()),
        messages: vec![Message {
            role: Role::User,
            content: format!(
                "Translate these factory results into plain English:\n\n{}",
                serde_json::to_string_pretty(&context).unwrap_or_default()
            ),
        }],
        max_tokens: 1024,
        temperature: 0.4,
        model: DefaultModels::TELEMETRY_PRESENTER.to_string(),
    };

    let response = router.complete(request).await?;
    let llm_report = parse_telemetry_response(&response.content)?;

    // Generate consequence cards if needed
    let mut consequence_cards = Vec::new();

    // Budget warning card
    if budget.status == BudgetStatus::Warning {
        consequence_cards.push(ConsequenceCardV1 {
            card_id: Uuid::new_v4(),
            project_id,
            trigger: CardTrigger::BudgetWarning,
            problem: format!(
                "This run has used ${:.2} of its ${:.2} budget.",
                budget.current_spend_usd, budget.hard_cap_usd,
            ),
            proposed_solution: "The run can continue, but you may want to review before it reaches the limit.".into(),
            impact: "If the budget runs out, the work will stop and you'll see what was completed.".into(),
            actions: vec![
                CardAction {
                    label: "Continue".into(),
                    description: "Let the run keep going within the current budget.".into(),
                },
                CardAction {
                    label: "Stop".into(),
                    description: "Stop the run now and review what's been done.".into(),
                },
            ],
            status: CardStatus::Pending,
            resolution: None,
        });
    }

    // Budget exhausted card
    if budget.status == BudgetStatus::HardStop {
        consequence_cards.push(ConsequenceCardV1 {
            card_id: Uuid::new_v4(),
            project_id,
            trigger: CardTrigger::BudgetExhausted,
            problem: format!(
                "This run reached its ${:.2} budget limit.",
                budget.hard_cap_usd,
            ),
            proposed_solution: "Here's what was completed. Want to continue with a new budget allocation?".into(),
            impact: "No more work will be done until you approve additional budget.".into(),
            actions: vec![
                CardAction {
                    label: "Add Budget".into(),
                    description: "Allocate more budget and continue from where we left off.".into(),
                },
                CardAction {
                    label: "Review First".into(),
                    description: "Let me see what was built before deciding.".into(),
                },
            ],
            status: CardStatus::Pending,
            resolution: None,
        });
    }

    // Critical gate failure card
    if satisfaction.critical_pass_rate < 1.0 {
        consequence_cards.push(ConsequenceCardV1 {
            card_id: Uuid::new_v4(),
            project_id,
            trigger: CardTrigger::CriticalGateFailure,
            problem: "Something critical didn't work as expected.".into(),
            proposed_solution: "I need to understand your intent better before trying again.".into(),
            impact: "The core functionality needs to work before we move forward.".into(),
            actions: vec![
                CardAction {
                    label: "Clarify".into(),
                    description: "Help me understand what should happen differently.".into(),
                },
                CardAction {
                    label: "Retry".into(),
                    description: "Try building it again with the same requirements.".into(),
                },
            ],
            status: CardStatus::Pending,
            resolution: None,
        });
    }

    // High gate failure card (only when critical passes but high fails)
    if satisfaction.critical_pass_rate >= 1.0 && satisfaction.high_pass_rate < 0.95 {
        // Collect the High-tier error categories for context
        let high_error_cats: Vec<&str> = satisfaction
            .scenario_results
            .iter()
            .filter(|r| r.tier == ScenarioTier::High && !r.majority_pass)
            .filter_map(|r| r.generalized_error.as_ref())
            .map(|e| e.category.as_str())
            .collect();

        let problem_detail = if high_error_cats.is_empty() {
            "Some important behaviors didn't work as expected.".into()
        } else {
            format!(
                "Some important behaviors didn't work as expected (areas: {}).",
                high_error_cats.join(", "),
            )
        };

        consequence_cards.push(ConsequenceCardV1 {
            card_id: Uuid::new_v4(),
            project_id,
            trigger: CardTrigger::HighGateFailure,
            problem: problem_detail,
            proposed_solution: "The core features work, but some important pieces need attention. I can retry or you can guide me.".into(),
            impact: "The app is mostly functional but some key behaviors are missing or incorrect.".into(),
            actions: vec![
                CardAction {
                    label: "Retry".into(),
                    description: "Let me try building those parts again.".into(),
                },
                CardAction {
                    label: "Clarify".into(),
                    description: "Tell me more about how these features should work.".into(),
                },
                CardAction {
                    label: "Accept".into(),
                    description: "It's good enough — move forward with what's built.".into(),
                },
            ],
            status: CardStatus::Pending,
            resolution: None,
        });
    }

    let satisfaction_message = satisfaction.user_message().to_string();
    let needs_user_action = llm_report.needs_user_action
        || !consequence_cards.is_empty()
        || !satisfaction.gates_passed;

    let preview_path = if factory_output.build_status == BuildStatus::Success
        || factory_output.build_status == BuildStatus::PartialSuccess
    {
        Some(factory_output.output_path.clone())
    } else {
        None
    };

    Ok(TelemetryReport {
        headline: llm_report.headline,
        summary: llm_report.summary,
        preview_path,
        needs_user_action,
        consequence_cards,
        satisfaction_message,
    })
}

/// Build a non-technical telemetry report WITHOUT an LLM call.
/// Used as a fallback when Haiku is unavailable, or for testing.
pub fn build_telemetry_report_deterministic(
    factory_output: &FactoryOutputV1,
    satisfaction: &SatisfactionResultV1,
    budget: &RunBudgetV1,
    _project_id: Uuid,
) -> TelemetryReport {
    let headline = match factory_output.build_status {
        BuildStatus::Success => satisfaction.user_message().to_string(),
        BuildStatus::PartialSuccess => "Your app is mostly built, but some pieces need work.".into(),
        BuildStatus::Failed => "The build didn't complete. Let me figure out what went wrong.".into(),
        BuildStatus::BudgetExhausted => format!(
            "The run used its full ${:.2} budget. Here's what got done.",
            budget.hard_cap_usd,
        ),
        BuildStatus::Error { ref message } => format!("Something unexpected happened: {}", message),
    };

    let nodes_done = factory_output.node_results.iter().filter(|n| n.success).count();
    let nodes_total = factory_output.node_results.len();

    let summary = format!(
        "{} Built {} of {} components. {}",
        satisfaction.user_message(),
        nodes_done,
        nodes_total,
        if satisfaction.gates_passed {
            "Ready for your review."
        } else {
            "Some things need attention before we continue."
        },
    );

    TelemetryReport {
        headline,
        summary,
        preview_path: Some(factory_output.output_path.clone()),
        needs_user_action: !satisfaction.gates_passed,
        consequence_cards: vec![],
        satisfaction_message: satisfaction.user_message().to_string(),
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn build_telemetry_context(
    factory_output: &FactoryOutputV1,
    satisfaction: &SatisfactionResultV1,
    budget: &RunBudgetV1,
) -> serde_json::Value {
    let failed_scenarios: Vec<&ScenarioResult> = satisfaction
        .scenario_results
        .iter()
        .filter(|r| !r.majority_pass)
        .collect();

    serde_json::json!({
        "build_status": format!("{:?}", factory_output.build_status),
        "nodes_completed": factory_output.node_results.iter()
            .filter(|n| n.success)
            .map(|n| &n.node_name)
            .collect::<Vec<_>>(),
        "nodes_failed": factory_output.node_results.iter()
            .filter(|n| !n.success)
            .map(|n| &n.node_name)
            .collect::<Vec<_>>(),
        "satisfaction_summary": satisfaction.user_message(),
        "gates_passed": satisfaction.gates_passed,
        "budget_status": format!("{:?}", budget.status),
        "budget_used_pct": if budget.hard_cap_usd > 0.0 {
            (budget.current_spend_usd / budget.hard_cap_usd * 100.0) as u32
        } else {
            0
        },
        "failed_scenario_count": failed_scenarios.len(),
        "failed_error_categories": failed_scenarios.iter()
            .filter_map(|r| r.generalized_error.as_ref())
            .map(|e| &e.category)
            .collect::<Vec<_>>(),
    })
}

/// Parsed telemetry response from Haiku.
#[derive(Debug)]
struct TelemetryLlmReport {
    headline: String,
    summary: String,
    needs_user_action: bool,
}

#[derive(Debug, serde::Deserialize)]
struct TelemetryJson {
    headline: String,
    summary: String,
    #[serde(default)]
    needs_user_action: bool,
    #[allow(dead_code)]
    action_description: Option<String>,
}

fn parse_telemetry_response(content: &str) -> StepResult<TelemetryLlmReport> {
    let cleaned = super::intake::strip_code_fences(content);

    let json: TelemetryJson = serde_json::from_str(&cleaned).map_err(|e| {
        StepError::JsonError(format!(
            "Failed to parse Telemetry Presenter response: {}. Raw: {}",
            e,
            &content[..content.len().min(300)]
        ))
    })?;

    Ok(TelemetryLlmReport {
        headline: json.headline,
        summary: json.summary,
        needs_user_action: json.needs_user_action,
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_telemetry_response() {
        let content = r#"{"headline": "Your app is ready!", "summary": "Everything built successfully. Take a look and tell me what you think.", "needs_user_action": false, "action_description": null}"#;
        let result = parse_telemetry_response(content);
        assert!(result.is_ok());
        let report = result.unwrap();
        assert_eq!(report.headline, "Your app is ready!");
        assert!(!report.needs_user_action);
    }

    #[test]
    fn parse_telemetry_with_action_needed() {
        let content = r#"{"headline": "Something needs your attention", "summary": "The core feature works but one important behavior didn't match. I need your input.", "needs_user_action": true, "action_description": "Tell me more about how the timer should reset."}"#;
        let result = parse_telemetry_response(content);
        assert!(result.is_ok());
        assert!(result.unwrap().needs_user_action);
    }

    #[test]
    fn deterministic_report_success() {
        let factory_output = FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Success,
            spend_usd: 0.42,
            checkpoint_path: "/tmp/checkpoint.json".into(),
            dod_results: vec![],
            node_results: vec![
                NodeResult {
                    node_name: "implement".into(),
                    success: true,
                    attempts: 1,
                    spend_usd: 0.30,
                    duration_secs: 20.0,
                    error: None,
                },
                NodeResult {
                    node_name: "verify".into(),
                    success: true,
                    attempts: 1,
                    spend_usd: 0.12,
                    duration_secs: 10.0,
                    error: None,
                },
            ],
            output_path: "/tmp/output".into(),
        };

        let satisfaction = SatisfactionResultV1 {
            kilroy_run_id: factory_output.kilroy_run_id,
            critical_pass_rate: 1.0,
            high_pass_rate: 1.0,
            medium_pass_rate: 1.0,
            gates_passed: true,
            scenario_results: vec![],
        };

        let budget = RunBudgetV1::new_phase0(Uuid::new_v4(), Uuid::new_v4());

        let report = build_telemetry_report_deterministic(
            &factory_output,
            &satisfaction,
            &budget,
            Uuid::new_v4(),
        );

        assert!(report.headline.contains("Everything works"));
        assert!(!report.needs_user_action);
        assert!(report.preview_path.is_some());
    }

    #[test]
    fn deterministic_report_failure() {
        let factory_output = FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Failed,
            spend_usd: 1.20,
            checkpoint_path: "/tmp/checkpoint.json".into(),
            dod_results: vec![],
            node_results: vec![
                NodeResult {
                    node_name: "implement".into(),
                    success: false,
                    attempts: 3,
                    spend_usd: 1.20,
                    duration_secs: 60.0,
                    error: Some("Build error".into()),
                },
            ],
            output_path: "/tmp/output".into(),
        };

        let satisfaction = SatisfactionResultV1 {
            kilroy_run_id: factory_output.kilroy_run_id,
            critical_pass_rate: 0.0,
            high_pass_rate: 0.0,
            medium_pass_rate: 0.0,
            gates_passed: false,
            scenario_results: vec![],
        };

        let budget = RunBudgetV1::new_phase0(Uuid::new_v4(), Uuid::new_v4());

        let report = build_telemetry_report_deterministic(
            &factory_output,
            &satisfaction,
            &budget,
            Uuid::new_v4(),
        );

        assert!(report.headline.contains("didn't complete"));
        assert!(report.needs_user_action);
    }

    #[test]
    fn build_telemetry_context_includes_all_fields() {
        let factory_output = FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Success,
            spend_usd: 0.30,
            checkpoint_path: "/tmp/cp.json".into(),
            dod_results: vec![],
            node_results: vec![],
            output_path: "/tmp/out".into(),
        };

        let satisfaction = SatisfactionResultV1 {
            kilroy_run_id: Uuid::new_v4(),
            critical_pass_rate: 1.0,
            high_pass_rate: 1.0,
            medium_pass_rate: 1.0,
            gates_passed: true,
            scenario_results: vec![],
        };

        let budget = RunBudgetV1::new_phase0(Uuid::new_v4(), Uuid::new_v4());

        let ctx = build_telemetry_context(&factory_output, &satisfaction, &budget);
        assert!(ctx.get("build_status").is_some());
        assert!(ctx.get("gates_passed").is_some());
        assert!(ctx.get("budget_status").is_some());
        assert!(ctx.get("satisfaction_summary").is_some());
    }

    #[test]
    fn high_gate_failure_generates_consequence_card() {
        let project_id = Uuid::new_v4();

        let factory_output = FactoryOutputV1 {
            kilroy_run_id: Uuid::new_v4(),
            nlspec_version: "1.0".into(),
            attempt: 1,
            build_status: BuildStatus::Success,
            spend_usd: 0.50,
            checkpoint_path: "/tmp/cp.json".into(),
            dod_results: vec![],
            node_results: vec![
                NodeResult {
                    node_name: "implement".into(),
                    success: true,
                    attempts: 1,
                    spend_usd: 0.50,
                    duration_secs: 30.0,
                    error: None,
                },
            ],
            output_path: "/tmp/out".into(),
        };

        // Critical passes, but High fails
        let satisfaction = SatisfactionResultV1 {
            kilroy_run_id: factory_output.kilroy_run_id,
            critical_pass_rate: 1.0,
            high_pass_rate: 0.80,
            medium_pass_rate: 0.90,
            gates_passed: false,
            scenario_results: vec![
                ScenarioResult {
                    scenario_id: "SC-HIGH-1".into(),
                    tier: ScenarioTier::High,
                    runs: [0.3, 0.4, 0.2],
                    majority_pass: false,
                    score: 0.3,
                    generalized_error: Some(GeneralizedError {
                        category: "state-management".into(),
                        severity: Severity::High,
                    }),
                },
            ],
        };

        let budget = RunBudgetV1::new_phase0(project_id, Uuid::new_v4());

        let report = build_telemetry_report_deterministic(
            &factory_output,
            &satisfaction,
            &budget,
            project_id,
        );

        // Should indicate user action needed since gates failed
        assert!(report.needs_user_action);
    }
}
