//! # Dependency Test Unit (DTU) — Schemas
//!
//! DTUs are stateful in-memory clones of external APIs used during
//! scenario validation. Instead of hitting real Stripe/Auth0/etc.,
//! the Scenario Validator talks to DTU clones that maintain realistic
//! state transitions.
//!
//! ## Phase 4: Stripe + Auth0
//! ## Phase 5: + SendGrid, Supabase, Twilio

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::turn::ArtifactPayload;

// ---------------------------------------------------------------------------
// DtuConfigV1 — Ralph-generated DTU configuration
// ---------------------------------------------------------------------------

/// Configuration for a DTU behavioral clone, generated by Ralph's
/// DTU Configuration mode when an ExternalDependency has `dtu_priority: High`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuConfigV1 {
    /// Which project this DTU config belongs to.
    pub project_id: Uuid,

    /// Name of the external dependency (e.g. "Stripe", "Auth0").
    pub dependency_name: String,

    /// Which DTU provider to use (maps to a registered DtuProvider).
    pub provider_id: String,

    /// Behavioral rules describing how the clone should behave.
    /// Generated by Ralph from the NLSpec's usage patterns.
    pub behavioral_rules: Vec<DtuBehavioralRule>,

    /// Initial state to seed the clone with (e.g. test users, products).
    pub seed_state: Vec<DtuSeedEntry>,

    /// Failure injection rules for edge-case scenario testing.
    pub failure_modes: Vec<DtuFailureMode>,

    /// Whether this config has been validated against the real API's behavior.
    pub validated: bool,
}

impl ArtifactPayload for DtuConfigV1 {
    const TYPE_ID: &'static str = "planner.dtu_config.v1";
}

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/// A behavioral rule describing expected API behavior.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuBehavioralRule {
    /// Rule ID (e.g. "STRIPE-RULE-1").
    pub id: String,

    /// Which API endpoint/operation this rule covers.
    pub endpoint: String,

    /// HTTP method (GET, POST, PUT, DELETE, etc.).
    pub method: String,

    /// Plain-English description of expected behavior.
    pub behavior: String,

    /// State transitions this operation causes.
    pub state_transitions: Vec<DtuStateTransition>,
}

/// A state transition caused by an API operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuStateTransition {
    /// Entity type affected (e.g. "payment_intent", "user").
    pub entity_type: String,

    /// State before the operation (e.g. "requires_payment_method").
    pub from_state: Option<String>,

    /// State after the operation (e.g. "requires_confirmation").
    pub to_state: String,
}

/// Seed data to initialize the DTU clone's state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuSeedEntry {
    /// Entity type (e.g. "customer", "product", "user").
    pub entity_type: String,

    /// Entity ID in the mock system.
    pub entity_id: String,

    /// JSON-serialized initial state.
    pub initial_state: serde_json::Value,
}

/// A failure mode for edge-case testing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuFailureMode {
    /// Failure ID (e.g. "STRIPE-FAIL-1").
    pub id: String,

    /// Which endpoint triggers this failure.
    pub endpoint: String,

    /// Trigger condition (e.g. "amount > 999999", "always", "nth_request:3").
    pub trigger: String,

    /// HTTP status code to return.
    pub status_code: u16,

    /// Error response body (JSON).
    pub error_body: serde_json::Value,

    /// Plain-English description of what this tests.
    pub description: String,
}

// ---------------------------------------------------------------------------
// DtuProvider registry types
// ---------------------------------------------------------------------------

/// Metadata for a registered DTU provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuProviderInfo {
    /// Provider ID (e.g. "stripe", "auth0", "sendgrid").
    pub id: String,

    /// Human-readable name.
    pub name: String,

    /// Supported API version (e.g. "2024-12-18.acacia" for Stripe).
    pub api_version: String,

    /// List of supported endpoints.
    pub supported_endpoints: Vec<String>,

    /// Phase in which this DTU was introduced.
    pub introduced_phase: u8,
}

/// A DTU HTTP request (input to the clone).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuRequest {
    /// HTTP method.
    pub method: String,

    /// Path (e.g. "/v1/payment_intents").
    pub path: String,

    /// Query parameters.
    pub query_params: Vec<(String, String)>,

    /// Request headers.
    pub headers: Vec<(String, String)>,

    /// Request body (JSON or form-encoded).
    pub body: Option<serde_json::Value>,
}

/// A DTU HTTP response (output from the clone).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DtuResponse {
    /// HTTP status code.
    pub status_code: u16,

    /// Response headers.
    pub headers: Vec<(String, String)>,

    /// Response body (JSON).
    pub body: serde_json::Value,
}
