//! # planner.git_commit.v1
//!
//! Git Projection commit record. Produced when the Smart Tinkerer
//! approves behavior in the Socratic Lobby. The resulting Git repo
//! runs without Planner v2 installed (anti-lock-in guarantee).

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::turn::ArtifactPayload;

// ---------------------------------------------------------------------------
// GitCommitV1
// ---------------------------------------------------------------------------

/// Record of a Git Projection commit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitCommitV1 {
    /// Which project this commit belongs to.
    pub project_id: Uuid,

    /// Git commit hash.
    pub commit_hash: String,

    /// Branch name (e.g. "main", "feature/add-stripe-checkout").
    pub branch: String,

    /// Human-readable commit message (generated by Telemetry Presenter).
    pub message: String,

    /// Files included in this commit.
    pub files: Vec<CommittedFile>,

    /// Which Kilroy run produced the code that was committed.
    pub kilroy_run_id: Uuid,

    /// Which preview snapshot was approved to trigger this commit.
    pub approved_preview_id: Uuid,
}

impl ArtifactPayload for GitCommitV1 {
    const TYPE_ID: &'static str = "planner.git_commit.v1";
}

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/// A file included in the Git Projection commit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommittedFile {
    /// Relative path within the repo (e.g. "src/app.tsx").
    pub path: String,

    /// What happened to this file.
    pub change_type: FileChangeType,
}

/// Type of file change in a commit.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum FileChangeType {
    Added,
    Modified,
    Deleted,
}
