//! # planner.graph_dot.v1
//!
//! Attractor-compatible DOT pipeline generated by the Compiler.
//! Kilroy reads this file and executes it via isolated Git worktrees.
//! The Compiler decides fidelity modes, goal_gate flags, model routing,
//! and retry budgets for each node.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::turn::ArtifactPayload;

// ---------------------------------------------------------------------------
// GraphDotV1
// ---------------------------------------------------------------------------

/// The Compiler's execution plan — a valid Graphviz DOT file that Kilroy
/// can consume via `kilroy attractor run`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphDotV1 {
    /// Which project this graph belongs to.
    pub project_id: Uuid,

    /// Version of the NLSpec this graph was generated from.
    pub nlspec_version: String,

    /// The raw DOT content — valid Graphviz, Attractor-compatible.
    pub dot_content: String,

    /// Number of execution nodes in the graph (excluding start/exit).
    pub node_count: u32,

    /// Pre-flight cost estimate for this graph execution.
    pub estimated_cost_usd: f32,

    /// Hard spend cap applied by the Factory Diplomat.
    pub run_budget_usd: f32,

    /// Summary of node-to-model routing decisions.
    pub model_routing: Vec<NodeModelAssignment>,
}

impl ArtifactPayload for GraphDotV1 {
    const TYPE_ID: &'static str = "planner.graph_dot.v1";
}

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/// Which LLM model is assigned to a specific DOT node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeModelAssignment {
    /// The DOT node name (e.g. "contracts", "auth", "api").
    pub node_name: String,

    /// The DOT node class (e.g. "implementation", "review").
    pub node_class: String,

    /// The LLM model assigned (e.g. "claude-sonnet-4-6", "gemini-3.1-pro").
    pub model: String,

    /// Fidelity mode (e.g. "truncate", "summary:low").
    pub fidelity: String,

    /// Whether this node has goal_gate=true (must succeed for pipeline to continue).
    pub goal_gate: bool,

    /// Max retries for this node.
    pub max_retries: u32,
}
